### ISSUE TITLE
Bug: NullPointerException al login.

### ISSUE THREAD

**Issue by Arkenan** [agufiuba/t2-android#1]
Actualmente es común que de un NullPointerException al intentar hacer login:

```  
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.view.View.requestFocus()' on a null object reference
at com.example.darius.taller_uber.LoginActivity.attemptLoginWithEmail(LoginActivity.java:317)
at com.example.darius.taller_uber.LoginActivity.access$100(LoginActivity.java:64)
at com.example.darius.taller_uber.LoginActivity$3.onClick(LoginActivity.java:135)
```

En resumen: En la función `attemptLoginWithEmail()`, llamada por el listener de clicks del botón de login, `getCurrentUser()` da `null`, entra al `if` y `focusView` resulta ser null.

**Comment by Arkenan** [comment]
Más info: el bug se produce cuando se ingresan usuario y o contraseña que no están registrados, pero de formato válido (`cancel = false`). El llamado a `getCurrentUser()` da null por dos motivos:

- El usuario o contraseña son incorrectos.
- Aún antes de que se pueda hacer el login en firebase, como es asincrónico, se ejecuta el chequeo de si es null. Es decir, incluso en el caso de que el usuario y la contraseña fueran correctos, es frecuente que se llegue a esta situación.

En ambos casos el elemento de foco no está asignado, dando `NullPointerException` en el `requestFocus`.

Esto se soluciona por ahora poniendo el request de foco en un else, solo para el caso de errores de formato.

Igual habría que revisar esto. Por ahí sea conveniente poner una barra de progreso o algo que bloquee la pantalla mientras se hace el login.

**Comment by Arkenan** [comment]
Esta NullPointerException queda entonces solucionada con el commit 4533d714c990db419f5f87ca95ca4693ace5d717.
